// Code generated by protoc-gen-go. DO NOT EDIT.
// source: integers.proto

package integers

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SingleInteger struct {
	Integer              *uint64  `protobuf:"varint,1,opt,name=integer" json:"integer,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SingleInteger) Reset()         { *m = SingleInteger{} }
func (m *SingleInteger) String() string { return proto.CompactTextString(m) }
func (*SingleInteger) ProtoMessage()    {}
func (*SingleInteger) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7d2a4376ec32b36, []int{0}
}

func (m *SingleInteger) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SingleInteger.Unmarshal(m, b)
}
func (m *SingleInteger) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SingleInteger.Marshal(b, m, deterministic)
}
func (m *SingleInteger) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SingleInteger.Merge(m, src)
}
func (m *SingleInteger) XXX_Size() int {
	return xxx_messageInfo_SingleInteger.Size(m)
}
func (m *SingleInteger) XXX_DiscardUnknown() {
	xxx_messageInfo_SingleInteger.DiscardUnknown(m)
}

var xxx_messageInfo_SingleInteger proto.InternalMessageInfo

func (m *SingleInteger) GetInteger() uint64 {
	if m != nil && m.Integer != nil {
		return *m.Integer
	}
	return 0
}

type HighFieldNum struct {
	IntegerA             *uint64  `protobuf:"varint,15,opt,name=integer_a,json=integerA" json:"integer_a,omitempty"`
	IntegerB             *uint64  `protobuf:"varint,16,opt,name=integer_b,json=integerB" json:"integer_b,omitempty"`
	IntegerC             *uint64  `protobuf:"varint,17,opt,name=integerC" json:"integerC,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HighFieldNum) Reset()         { *m = HighFieldNum{} }
func (m *HighFieldNum) String() string { return proto.CompactTextString(m) }
func (*HighFieldNum) ProtoMessage()    {}
func (*HighFieldNum) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7d2a4376ec32b36, []int{1}
}

func (m *HighFieldNum) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HighFieldNum.Unmarshal(m, b)
}
func (m *HighFieldNum) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HighFieldNum.Marshal(b, m, deterministic)
}
func (m *HighFieldNum) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HighFieldNum.Merge(m, src)
}
func (m *HighFieldNum) XXX_Size() int {
	return xxx_messageInfo_HighFieldNum.Size(m)
}
func (m *HighFieldNum) XXX_DiscardUnknown() {
	xxx_messageInfo_HighFieldNum.DiscardUnknown(m)
}

var xxx_messageInfo_HighFieldNum proto.InternalMessageInfo

func (m *HighFieldNum) GetIntegerA() uint64 {
	if m != nil && m.IntegerA != nil {
		return *m.IntegerA
	}
	return 0
}

func (m *HighFieldNum) GetIntegerB() uint64 {
	if m != nil && m.IntegerB != nil {
		return *m.IntegerB
	}
	return 0
}

func (m *HighFieldNum) GetIntegerC() uint64 {
	if m != nil && m.IntegerC != nil {
		return *m.IntegerC
	}
	return 0
}

type SignedInteger struct {
	Integer              *int32   `protobuf:"varint,1,opt,name=integer" json:"integer,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignedInteger) Reset()         { *m = SignedInteger{} }
func (m *SignedInteger) String() string { return proto.CompactTextString(m) }
func (*SignedInteger) ProtoMessage()    {}
func (*SignedInteger) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7d2a4376ec32b36, []int{2}
}

func (m *SignedInteger) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignedInteger.Unmarshal(m, b)
}
func (m *SignedInteger) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignedInteger.Marshal(b, m, deterministic)
}
func (m *SignedInteger) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignedInteger.Merge(m, src)
}
func (m *SignedInteger) XXX_Size() int {
	return xxx_messageInfo_SignedInteger.Size(m)
}
func (m *SignedInteger) XXX_DiscardUnknown() {
	xxx_messageInfo_SignedInteger.DiscardUnknown(m)
}

var xxx_messageInfo_SignedInteger proto.InternalMessageInfo

func (m *SignedInteger) GetInteger() int32 {
	if m != nil && m.Integer != nil {
		return *m.Integer
	}
	return 0
}

type UnSignedInteger struct {
	Integer              *uint64  `protobuf:"varint,1,opt,name=integer" json:"integer,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnSignedInteger) Reset()         { *m = UnSignedInteger{} }
func (m *UnSignedInteger) String() string { return proto.CompactTextString(m) }
func (*UnSignedInteger) ProtoMessage()    {}
func (*UnSignedInteger) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7d2a4376ec32b36, []int{3}
}

func (m *UnSignedInteger) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnSignedInteger.Unmarshal(m, b)
}
func (m *UnSignedInteger) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnSignedInteger.Marshal(b, m, deterministic)
}
func (m *UnSignedInteger) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnSignedInteger.Merge(m, src)
}
func (m *UnSignedInteger) XXX_Size() int {
	return xxx_messageInfo_UnSignedInteger.Size(m)
}
func (m *UnSignedInteger) XXX_DiscardUnknown() {
	xxx_messageInfo_UnSignedInteger.DiscardUnknown(m)
}

var xxx_messageInfo_UnSignedInteger proto.InternalMessageInfo

func (m *UnSignedInteger) GetInteger() uint64 {
	if m != nil && m.Integer != nil {
		return *m.Integer
	}
	return 0
}

type SignedInteger2 struct {
	Integer              *int64   `protobuf:"varint,1,opt,name=integer" json:"integer,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignedInteger2) Reset()         { *m = SignedInteger2{} }
func (m *SignedInteger2) String() string { return proto.CompactTextString(m) }
func (*SignedInteger2) ProtoMessage()    {}
func (*SignedInteger2) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7d2a4376ec32b36, []int{4}
}

func (m *SignedInteger2) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignedInteger2.Unmarshal(m, b)
}
func (m *SignedInteger2) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignedInteger2.Marshal(b, m, deterministic)
}
func (m *SignedInteger2) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignedInteger2.Merge(m, src)
}
func (m *SignedInteger2) XXX_Size() int {
	return xxx_messageInfo_SignedInteger2.Size(m)
}
func (m *SignedInteger2) XXX_DiscardUnknown() {
	xxx_messageInfo_SignedInteger2.DiscardUnknown(m)
}

var xxx_messageInfo_SignedInteger2 proto.InternalMessageInfo

func (m *SignedInteger2) GetInteger() int64 {
	if m != nil && m.Integer != nil {
		return *m.Integer
	}
	return 0
}

type StringMessage struct {
	S                    *string  `protobuf:"bytes,1,opt,name=s" json:"s,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StringMessage) Reset()         { *m = StringMessage{} }
func (m *StringMessage) String() string { return proto.CompactTextString(m) }
func (*StringMessage) ProtoMessage()    {}
func (*StringMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7d2a4376ec32b36, []int{5}
}

func (m *StringMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StringMessage.Unmarshal(m, b)
}
func (m *StringMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StringMessage.Marshal(b, m, deterministic)
}
func (m *StringMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StringMessage.Merge(m, src)
}
func (m *StringMessage) XXX_Size() int {
	return xxx_messageInfo_StringMessage.Size(m)
}
func (m *StringMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_StringMessage.DiscardUnknown(m)
}

var xxx_messageInfo_StringMessage proto.InternalMessageInfo

func (m *StringMessage) GetS() string {
	if m != nil && m.S != nil {
		return *m.S
	}
	return ""
}

type TopMessage struct {
	M                    *EmbeddedMessage `protobuf:"bytes,1,opt,name=m" json:"m,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *TopMessage) Reset()         { *m = TopMessage{} }
func (m *TopMessage) String() string { return proto.CompactTextString(m) }
func (*TopMessage) ProtoMessage()    {}
func (*TopMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7d2a4376ec32b36, []int{6}
}

func (m *TopMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TopMessage.Unmarshal(m, b)
}
func (m *TopMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TopMessage.Marshal(b, m, deterministic)
}
func (m *TopMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TopMessage.Merge(m, src)
}
func (m *TopMessage) XXX_Size() int {
	return xxx_messageInfo_TopMessage.Size(m)
}
func (m *TopMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_TopMessage.DiscardUnknown(m)
}

var xxx_messageInfo_TopMessage proto.InternalMessageInfo

func (m *TopMessage) GetM() *EmbeddedMessage {
	if m != nil {
		return m.M
	}
	return nil
}

type EmbeddedMessage struct {
	I                    *uint64  `protobuf:"varint,1,opt,name=i" json:"i,omitempty"`
	S                    *string  `protobuf:"bytes,2,opt,name=s" json:"s,omitempty"`
	B                    *bool    `protobuf:"varint,3,opt,name=b" json:"b,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmbeddedMessage) Reset()         { *m = EmbeddedMessage{} }
func (m *EmbeddedMessage) String() string { return proto.CompactTextString(m) }
func (*EmbeddedMessage) ProtoMessage()    {}
func (*EmbeddedMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7d2a4376ec32b36, []int{7}
}

func (m *EmbeddedMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmbeddedMessage.Unmarshal(m, b)
}
func (m *EmbeddedMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmbeddedMessage.Marshal(b, m, deterministic)
}
func (m *EmbeddedMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmbeddedMessage.Merge(m, src)
}
func (m *EmbeddedMessage) XXX_Size() int {
	return xxx_messageInfo_EmbeddedMessage.Size(m)
}
func (m *EmbeddedMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_EmbeddedMessage.DiscardUnknown(m)
}

var xxx_messageInfo_EmbeddedMessage proto.InternalMessageInfo

func (m *EmbeddedMessage) GetI() uint64 {
	if m != nil && m.I != nil {
		return *m.I
	}
	return 0
}

func (m *EmbeddedMessage) GetS() string {
	if m != nil && m.S != nil {
		return *m.S
	}
	return ""
}

func (m *EmbeddedMessage) GetB() bool {
	if m != nil && m.B != nil {
		return *m.B
	}
	return false
}

func init() {
	proto.RegisterType((*SingleInteger)(nil), "integers.SingleInteger")
	proto.RegisterType((*HighFieldNum)(nil), "integers.HighFieldNum")
	proto.RegisterType((*SignedInteger)(nil), "integers.SignedInteger")
	proto.RegisterType((*UnSignedInteger)(nil), "integers.UnSignedInteger")
	proto.RegisterType((*SignedInteger2)(nil), "integers.SignedInteger2")
	proto.RegisterType((*StringMessage)(nil), "integers.StringMessage")
	proto.RegisterType((*TopMessage)(nil), "integers.TopMessage")
	proto.RegisterType((*EmbeddedMessage)(nil), "integers.EmbeddedMessage")
}

func init() { proto.RegisterFile("integers.proto", fileDescriptor_e7d2a4376ec32b36) }

var fileDescriptor_e7d2a4376ec32b36 = []byte{
	// 244 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x90, 0x41, 0x4b, 0x03, 0x31,
	0x10, 0x85, 0x19, 0xab, 0xd8, 0x8e, 0x6d, 0x57, 0x73, 0x8a, 0x8a, 0x50, 0x72, 0xb1, 0x2a, 0xf4,
	0x50, 0xf0, 0xe4, 0x49, 0x8b, 0xa2, 0x07, 0x3d, 0xa4, 0x7a, 0x96, 0x86, 0x0c, 0x31, 0xd0, 0x64,
	0xcb, 0x66, 0xfd, 0xff, 0xd2, 0xdd, 0xc4, 0xee, 0x2e, 0xe8, 0x2d, 0x6f, 0xbe, 0x8f, 0x99, 0x47,
	0x70, 0x6c, 0x7d, 0x49, 0x86, 0x8a, 0x30, 0xdb, 0x14, 0x79, 0x99, 0xb3, 0x7e, 0xca, 0xe2, 0x0a,
	0x47, 0x4b, 0xeb, 0xcd, 0x9a, 0x5e, 0xea, 0x09, 0xe3, 0x78, 0x18, 0x21, 0x87, 0x09, 0x4c, 0xf7,
	0x65, 0x8a, 0x42, 0xe3, 0xf0, 0xd9, 0x9a, 0xaf, 0x27, 0x4b, 0x6b, 0xfd, 0xf6, 0xed, 0xd8, 0x39,
	0x0e, 0x22, 0xfa, 0x5c, 0xf1, 0xac, 0x72, 0xd3, 0xde, 0xfb, 0x26, 0x54, 0xfc, 0xb8, 0x05, 0x1f,
	0xd8, 0x19, 0xa6, 0xf7, 0x82, 0x9f, 0xb4, 0xd8, 0xa2, 0x2e, 0x64, 0x3c, 0xe9, 0x3f, 0x0a, 0x1d,
	0xec, 0x0a, 0xdd, 0x60, 0xf6, 0xe1, 0xff, 0x95, 0x1b, 0xed, 0xaf, 0x71, 0xdc, 0x52, 0xe7, 0x5d,
	0xb7, 0xb7, 0x73, 0x2f, 0x70, 0xb4, 0x2c, 0x0b, 0xeb, 0xcd, 0x2b, 0x85, 0xb0, 0x32, 0xc4, 0x86,
	0x08, 0xa1, 0x92, 0x06, 0x12, 0x82, 0xb8, 0x45, 0x7c, 0xcf, 0x37, 0x89, 0x5d, 0x22, 0xb8, 0x8a,
	0x1d, 0xcd, 0x4f, 0x67, 0xbf, 0xff, 0xfc, 0xe8, 0x14, 0x69, 0x4d, 0x3a, 0x5a, 0x12, 0x9c, 0xb8,
	0xc3, 0xac, 0x33, 0xdd, 0xee, 0xb5, 0xb1, 0x28, 0xd8, 0xfa, 0xca, 0x5e, 0xbc, 0xb2, 0x4d, 0x8a,
	0xf7, 0x26, 0x30, 0xed, 0x4b, 0x50, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x3d, 0x63, 0xd4, 0xe2,
	0xc2, 0x01, 0x00, 0x00,
}
