// Code generated by protoc-gen-go. DO NOT EDIT.
// source: repeated.proto

package repeated

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RepeatedInteger struct {
	Integer              []uint64 `protobuf:"varint,1,rep,name=integer" json:"integer,omitempty"`
	PackedInteger        []uint64 `protobuf:"varint,2,rep,packed,name=packed_integer,json=packedInteger" json:"packed_integer,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RepeatedInteger) Reset()         { *m = RepeatedInteger{} }
func (m *RepeatedInteger) String() string { return proto.CompactTextString(m) }
func (*RepeatedInteger) ProtoMessage()    {}
func (*RepeatedInteger) Descriptor() ([]byte, []int) {
	return fileDescriptor_705b304fd1c9cbf2, []int{0}
}

func (m *RepeatedInteger) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RepeatedInteger.Unmarshal(m, b)
}
func (m *RepeatedInteger) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RepeatedInteger.Marshal(b, m, deterministic)
}
func (m *RepeatedInteger) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RepeatedInteger.Merge(m, src)
}
func (m *RepeatedInteger) XXX_Size() int {
	return xxx_messageInfo_RepeatedInteger.Size(m)
}
func (m *RepeatedInteger) XXX_DiscardUnknown() {
	xxx_messageInfo_RepeatedInteger.DiscardUnknown(m)
}

var xxx_messageInfo_RepeatedInteger proto.InternalMessageInfo

func (m *RepeatedInteger) GetInteger() []uint64 {
	if m != nil {
		return m.Integer
	}
	return nil
}

func (m *RepeatedInteger) GetPackedInteger() []uint64 {
	if m != nil {
		return m.PackedInteger
	}
	return nil
}

func init() {
	proto.RegisterType((*RepeatedInteger)(nil), "repeated.RepeatedInteger")
}

func init() { proto.RegisterFile("repeated.proto", fileDescriptor_705b304fd1c9cbf2) }

var fileDescriptor_705b304fd1c9cbf2 = []byte{
	// 99 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2b, 0x4a, 0x2d, 0x48,
	0x4d, 0x2c, 0x49, 0x4d, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x80, 0xf1, 0x95, 0xc2,
	0xb8, 0xf8, 0x83, 0xa0, 0x6c, 0xcf, 0xbc, 0x92, 0xd4, 0xf4, 0xd4, 0x22, 0x21, 0x09, 0x2e, 0xf6,
	0x4c, 0x08, 0x53, 0x82, 0x51, 0x81, 0x59, 0x83, 0x25, 0x08, 0xc6, 0x15, 0xd2, 0xe4, 0xe2, 0x2b,
	0x48, 0x4c, 0xce, 0x4e, 0x4d, 0x89, 0x87, 0x29, 0x60, 0x02, 0x29, 0x70, 0x62, 0x12, 0x60, 0x0c,
	0xe2, 0x85, 0xc8, 0x40, 0x0d, 0x01, 0x04, 0x00, 0x00, 0xff, 0xff, 0x0a, 0xaf, 0xe0, 0xe5, 0x72,
	0x00, 0x00, 0x00,
}
