// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protostrings.proto

package protostrings

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ProtoString struct {
	S                    *string  `protobuf:"bytes,1,opt,name=s" json:"s,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProtoString) Reset()         { *m = ProtoString{} }
func (m *ProtoString) String() string { return proto.CompactTextString(m) }
func (*ProtoString) ProtoMessage()    {}
func (*ProtoString) Descriptor() ([]byte, []int) {
	return fileDescriptor_3e179df801ea3bfa, []int{0}
}

func (m *ProtoString) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtoString.Unmarshal(m, b)
}
func (m *ProtoString) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtoString.Marshal(b, m, deterministic)
}
func (m *ProtoString) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtoString.Merge(m, src)
}
func (m *ProtoString) XXX_Size() int {
	return xxx_messageInfo_ProtoString.Size(m)
}
func (m *ProtoString) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtoString.DiscardUnknown(m)
}

var xxx_messageInfo_ProtoString proto.InternalMessageInfo

func (m *ProtoString) GetS() string {
	if m != nil && m.S != nil {
		return *m.S
	}
	return ""
}

func init() {
	proto.RegisterType((*ProtoString)(nil), "protostrings.ProtoString")
}

func init() { proto.RegisterFile("protostrings.proto", fileDescriptor_3e179df801ea3bfa) }

var fileDescriptor_3e179df801ea3bfa = []byte{
	// 68 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2a, 0x28, 0xca, 0x2f,
	0xc9, 0x2f, 0x2e, 0x29, 0xca, 0xcc, 0x4b, 0x2f, 0xd6, 0x03, 0x73, 0x84, 0x78, 0x90, 0xc5, 0x94,
	0xa4, 0xb9, 0xb8, 0x03, 0x40, 0xfc, 0x60, 0x30, 0x5f, 0x88, 0x87, 0x8b, 0xb1, 0x58, 0x82, 0x51,
	0x81, 0x51, 0x83, 0x33, 0x88, 0xb1, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0xb0, 0x65, 0x75, 0xe9,
	0x3f, 0x00, 0x00, 0x00,
}
